from google.adk.agents import Agent
from google.adk.models import Gemini
from google.genai import types
from ..config import settings
from typing import Dict, Any, List, Optional, Union

from a2ui.schema.manager import A2uiSchemaManager
from a2ui.basic_catalog.provider import BasicCatalog
from a2ui.schema.constants import VERSION_0_9_1

schema_manager = A2uiSchemaManager(
    version=VERSION_0_9_1,
    catalogs=[BasicCatalog.get_config(version=VERSION_0_9_1)]
)

def dynamic_instruction(ctx):
    blueprint = ctx.state.get("blueprint", "")
    description = ctx.state.get("description", "")
    
    if hasattr(blueprint, "model_dump_json"):
        blueprint = blueprint.model_dump_json()
    elif isinstance(blueprint, dict):
        import json
        blueprint = json.dumps(blueprint, indent=2)
    else:
        blueprint = str(blueprint)
        

    ui_desc = (
        "Generate a complete A2UI JSON payload that represents this calculator.\n"
        "TAG WRAPPING REQUIREMENT: You MUST wrap the entire JSON payload in `<a2ui-json>` and `</a2ui-json>` tags. Output ONLY the tagged JSON payload, without any surrounding conversational text, explanations, or markdown code blocks (unless the tags are inside it).\n"
        "HEADER COMPONENTS REQUIREMENT: You MUST include two Text components at the very top of your \"components\" list: first, a component with ID \"title-text\" containing the user-oriented title, and second, a component with ID \"description-text\" containing the user-oriented description.\n"
        "IMPORTANT: You MUST output exactly ONE JSON array containing BOTH an `updateComponents` message and an `updateDataModel` message. Do not split them into separate blocks.\n"
        "CRITICAL: The component tree MUST BE COMPLETELY FLAT. Container components (Column, Row, Card, Button) CANNOT contain inline object definitions for their children. You MUST reference children exclusively by their string IDs and place all actual component objects at the root level of the components array.\n"
        "DATA BINDING SYNTAX: A2UI uses JSON objects for state binding. You MUST NOT use string templates like `${/weight}`. If you use `${/weight}` the validation will CRASH. You MUST strictly use the object format: `{ \"path\": \"/weight\" }` for bindings.\n"
        "TEXT COMPONENT RESULT BINDING: For Text components that display calculation results, you MUST use object binding (e.g., `\"text\": {\"path\": \"/bmi_value\"}`). The path MUST exactly match the output variable keys defined in the backend blueprint. Do NOT use string interpolation like `${/bmi_value}` or `{{bmi_value}}`.\n"
        "DEFAULT VALUES: If appropriate, input values in the `updateDataModel` message should have reasonable default values instead of null so the UI isn't completely empty when first loaded.\n"
        "SLIDERS FOR RANGES: For values which have a reasonable real-life range, create both an input field and a slider bound to the same parameter (as demonstrated in the example below).\n"
        "SLIDER LIMITATIONS: Create slider components only if they can be represented in integer range, otherwise - use input field only. Use strict integer values for `min` and `max` (e.g., `10` and `300` rather than `10.0` or `10.5`)"
        "CHOICEPICKER BINDING: ChoicePicker stores its selections as an array of strings, even when variant is 'mutuallyExclusive'. Initialize these values as arrays (e.g., `\"weight_unit\": [\"kg\"]`). When passing these in the calculate button payload, map directly (e.g., `{\"path\": \"/weight_unit\"}`). Do NOT use array indexing.\n"
        "EXACT COMPONENT MAPPING: The backend blueprint's `component_type` (e.g., 'ChoicePicker', 'TextField', 'Slider', 'CheckBox') MUST be respected. If a parameter specifies `component_type: \"ChoicePicker\"`, you MUST use an A2UI `ChoicePicker` component. This guarantees the UI matches the python script's expectations.\n"
        "INPUT VALIDATION CHECKS: For input components (like TextField), you MUST define a `checks` array if validation rules (like required, min_value, max_value, pattern) are specified in the parameter definitions of the blueprint. Set up checks using function calls (e.g., `call: \"required\"`, `call: \"numeric\"` with `min` and `max` arguments, or `call: \"regex\"` with a `pattern` argument) wrapped inside the `condition` property of each CheckRule, and include user-friendly error messages (e.g. \"Weight is required.\").\n"
        "EXAMPLE OF A COMPLETE, CORRECT, FULLY FLAT A2UI PAYLOAD:\n"
        "```json\n"
        "[\n"
        "  {\n"
        "    \"version\": \"v0.9\",\n"
        "    \"updateComponents\": {\n"
        "      \"surfaceId\": \"calculator-surface\",\n"
        "      \"components\": [\n"
        "        {\n"
        "          \"id\": \"title-text\",\n"
        "          \"component\": \"Text\",\n"
        "          \"variant\": \"h4\",\n"
        "          \"text\": \"Body Mass Index (BMI) Calculator\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"description-text\",\n"
        "          \"component\": \"Text\",\n"
        "          \"variant\": \"body\",\n"
        "          \"text\": \"The Body Mass Index (BMI) calculator determines your health category by calculating the relationship between your weight and height, offering support for both metric and imperial measurement units.\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"root\",\n"
        "          \"component\": \"Column\",\n"
        "          \"children\": [\n"
        "            \"main-card\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"main-card\",\n"
        "          \"component\": \"Card\",\n"
        "          \"child\": \"main-column\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"main-column\",\n"
        "          \"component\": \"Column\",\n"
        "          \"children\": [\n"
        "            \"title-text\",\n"
        "            \"description-text\",\n"
        "            \"weight-row\",\n"
        "            \"weight-slider\",\n"
        "            \"height-row\",\n"
        "            \"height-slider\",\n"
        "            \"calculate-button\",\n"
        "            \"results-card\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"weight-row\",\n"
        "          \"component\": \"Row\",\n"
        "          \"align\": \"end\",\n"
        "          \"children\": [\n"
        "            \"weight-input\",\n"
        "            \"weight-unit-picker\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"weight-input\",\n"
        "          \"component\": \"TextField\",\n"
        "          \"label\": \"Weight\",\n"
        "          \"variant\": \"number\",\n"
        "          \"value\": {\n"
        "            \"path\": \"/weight\"\n"
        "          },\n"
        "          \"weight\": 1,\n"
        "          \"checks\": [\n"
        "            {\n"
        "              \"condition\": {\n"
        "                \"call\": \"required\",\n"
        "                \"args\": {\n"
        "                  \"value\": {\n"
        "                    \"path\": \"/weight\"\n"
        "                  }\n"
        "                }\n"
        "              },\n"
        "              \"message\": \"Weight is required.\"\n"
        "            },\n"
        "            {\n"
        "              \"condition\": {\n"
        "                \"call\": \"numeric\",\n"
        "                \"args\": {\n"
        "                  \"value\": {\n"
        "                    \"path\": \"/weight\"\n"
        "                  },\n"
        "                  \"min\": 0.1,\n"
        "                  \"max\": 1000.0\n"
        "                }\n"
        "              },\n"
        "              \"message\": \"Weight must be between 0.1 and 1000.0.\"\n"
        "            }\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"weight-unit-picker\",\n"
        "          \"component\": \"ChoicePicker\",\n"
        "          \"label\": \"\",\n"
        "          \"variant\": \"mutuallyExclusive\",\n"
        "          \"displayStyle\": \"chips\",\n"
        "          \"value\": {\n"
        "            \"path\": \"/weight_unit\"\n"
        "          },\n"
        "          \"options\": [\n"
        "            {\n"
        "              \"label\": \"kg\",\n"
        "              \"value\": \"kg\"\n"
        "            },\n"
        "            {\n"
        "              \"label\": \"lb\",\n"
        "              \"value\": \"lb\"\n"
        "            }\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"weight-slider\",\n"
        "          \"component\": \"Slider\",\n"
        "          \"min\": 10.0,\n"
        "          \"max\": 300.0,\n"
        "          \"step\": 1.0,\n"
        "          \"value\": {\n"
        "            \"path\": \"/weight\"\n"
        "          }\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"height-row\",\n"
        "          \"component\": \"Row\",\n"
        "          \"align\": \"end\",\n"
        "          \"children\": [\n"
        "            \"height-input\",\n"
        "            \"height-unit-picker\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"height-input\",\n"
        "          \"component\": \"TextField\",\n"
        "          \"label\": \"Height\",\n"
        "          \"variant\": \"number\",\n"
        "          \"value\": {\n"
        "            \"path\": \"/height\"\n"
        "          },\n"
        "          \"weight\": 1,\n"
        "          \"checks\": [\n"
        "            {\n"
        "              \"condition\": {\n"
        "                \"call\": \"required\",\n"
        "                \"args\": {\n"
        "                  \"value\": {\n"
        "                    \"path\": \"/height\"\n"
        "                  }\n"
        "                }\n"
        "              },\n"
        "              \"message\": \"Height is required.\"\n"
        "            },\n"
        "            {\n"
        "              \"condition\": {\n"
        "                \"call\": \"numeric\",\n"
        "                \"args\": {\n"
        "                  \"value\": {\n"
        "                    \"path\": \"/height\"\n"
        "                  },\n"
        "                  \"min\": 0.1,\n"
        "                  \"max\": 300.0\n"
        "                }\n"
        "              },\n"
        "              \"message\": \"Height must be between 0.1 and 300.0.\"\n"
        "            }\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"height-unit-picker\",\n"
        "          \"component\": \"ChoicePicker\",\n"
        "          \"label\": \"\",\n"
        "          \"variant\": \"mutuallyExclusive\",\n"
        "          \"displayStyle\": \"chips\",\n"
        "          \"value\": {\n"
        "            \"path\": \"/height_unit\"\n"
        "          },\n"
        "          \"options\": [\n"
        "            {\n"
        "              \"label\": \"m\",\n"
        "              \"value\": \"m\"\n"
        "            },\n"
        "            {\n"
        "              \"label\": \"cm\",\n"
        "              \"value\": \"cm\"\n"
        "            },\n"
        "            {\n"
        "              \"label\": \"in\",\n"
        "              \"value\": \"in\"\n"
        "            }\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"height-slider\",\n"
        "          \"component\": \"Slider\",\n"
        "          \"min\": 30.0,\n"
        "          \"max\": 250.0,\n"
        "          \"step\": 1.0,\n"
        "          \"value\": {\n"
        "            \"path\": \"/height\"\n"
        "          }\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"calculate-button\",\n"
        "          \"component\": \"Button\",\n"
        "          \"variant\": \"primary\",\n"
        "          \"child\": \"calculate-button-text\",\n"
        "          \"action\": {\n"
        "            \"event\": {\n"
        "              \"name\": \"calculate\",\n"
        "              \"context\": {\n"
        "                \"weight\": {\n"
        "                  \"path\": \"/weight\"\n"
        "                },\n"
        "                \"weight_unit\": {\n"
        "                  \"path\": \"/weight_unit\"\n"
        "                },\n"
        "                \"height\": {\n"
        "                  \"path\": \"/height\"\n"
        "                },\n"
        "                \"height_unit\": {\n"
        "                  \"path\": \"/height_unit\"\n"
        "                }\n"
        "              }\n"
        "            }\n"
        "          }\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"calculate-button-text\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": \"Calculate BMI\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"results-card\",\n"
        "          \"component\": \"Card\",\n"
        "          \"child\": \"results-column\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"results-column\",\n"
        "          \"component\": \"Column\",\n"
        "          \"children\": [\n"
        "            \"bmi-result-row\",\n"
        "            \"category-result-row\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"bmi-result-row\",\n"
        "          \"component\": \"Row\",\n"
        "          \"justify\": \"spaceBetween\",\n"
        "          \"children\": [\n"
        "            \"bmi-result-label\",\n"
        "            \"bmi-result-value\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"bmi-result-label\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": \"BMI\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"bmi-result-value\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": {\n"
        "            \"path\": \"/bmi\"\n"
        "          }\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"category-result-row\",\n"
        "          \"component\": \"Row\",\n"
        "          \"justify\": \"spaceBetween\",\n"
        "          \"children\": [\n"
        "            \"category-result-label\",\n"
        "            \"category-result-value\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"category-result-label\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": \"Category\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"category-result-value\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": {\n"
        "            \"path\": \"/category\"\n"
        "          }\n"
        "        }\n"
        "      ]\n"
        "    }\n"
        "  },\n"
        "  {\n"
        "    \"version\": \"v0.9\",\n"
        "    \"updateDataModel\": {\n"
        "      \"surfaceId\": \"calculator-surface\",\n"
        "      \"value\": {\n"
        "        \"weight\": 70.0,\n"
        "        \"weight_unit\": [\"kg\"],\n"
        "        \"height\": 170.0,\n"
        "        \"height_unit\": [\"cm\"],\n"
        "        \"bmi\": null,\n"
        "        \"category\": null\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "]\n"
        "```\n"
        "Ensure the components map to all inputs and results defined in the blueprint, and include a calculate button that triggers the 'calculate' action.\n"
        "DO NOT output any conversational text, explanations, or apologies. You MUST wrap the entire JSON payload in `<a2ui-json>` and `</a2ui-json>` tags. Output ONLY the tagged JSON payload."
    )
    
    validation_err = ctx.state.get("ui_validation_error", "")
    if validation_err:
        ui_desc += f"\n\nCRITICAL ERROR IN PREVIOUS ATTEMPT: Your previous JSON payload failed validation with these exact errors:\n{validation_err}\n\nYOU MUST FIX THESE ERRORS and strictly adhere to the flat component tree requirement.\nAGAIN: NO explanations, NO apologies. JUST RETURN THE FIXED JSON SCHEMA."

    return schema_manager.generate_system_prompt(
        role_description="You are a frontend generator that outputs a valid A2UI declarative JSON schema payload.",
        workflow_description=(
            "Generate a complete A2UI JSON payload for a calculator based STRICTLY on this blueprint:\n\n"
            f"{blueprint}\n\n"
            "User description of this calculator:\n"
            f"{description}"
        ),
        ui_description=ui_desc,
        include_schema=True,
        include_examples=True,
        allowed_components=["Column", "Row", "Card", "TextField", "Slider", "ChoicePicker", "Text", "Button"]
    )

ui_schema_generator = Agent(
    name="ui_schema_generator",
    model=settings.model_coding,
    include_contents='none',
    instruction=dynamic_instruction,
    # No output_schema to avoid Vertex AI function calling restrictions. 
    # A2UI SDK provides prompt instructions to generate the JSON, and parser to validate it.
)
