"""UI Schema Generator Agent Node.

This is the most complex node in the Manyculator workflow graph. It constructs
a detailed A2UI (Agent-to-UI) instruction prompt and feeds it to an LLM that
generates a complete declarative JSON UI schema for the calculator.

Architectural Role:
    This node sits between the blueprint_generator and the ui_schema_validator
    in the workflow. It receives a blueprint (describing inputs, outputs, and
    calculation logic) and produces a renderable A2UI JSON payload that any
    A2UI-compatible client can display as an interactive calculator form.

Prompt Engineering Strategy:
    The LLM must produce pixel-perfect, schema-valid A2UI JSON on the first
    attempt. To achieve this, the instruction prompt is constructed in layers:

    1. **A2UI System Prompt** — Generated by ``A2uiSchemaManager``, this
       injects the full A2UI JSON schema specification and component catalog
       into the system prompt so the LLM knows every valid property and type.
    2. **Explicit Structural Rules** — A long list of MUST/MUST NOT rules
       (flat tree, binding syntax, ChoicePicker arrays, etc.) that address
       the most common LLM mistakes observed during development.
    3. **Complete BMI Calculator Example** — A fully worked-out, valid A2UI
       payload (~300 lines of JSON) embedded directly in the prompt. This
       "show, don't tell" approach dramatically reduces structural errors
       because the LLM can pattern-match against a real, correct example
       rather than infer the JSON structure from abstract schema rules alone.
    4. **Validation Error Feedback** — On retry loops, the exact validation
       errors from the previous attempt are appended so the LLM can self-
       correct without losing the original context.

Why ``output_schema`` is NOT used:
    Passing an ``output_schema`` forces Vertex AI to return a function call
    object rather than raw text. Since the UI schema is a massive JSON payload,
    we skip ``output_schema`` and tell the LLM to output raw text wrapped in
    ``<a2ui-json>`` tags. The downstream ``ui_schema_validator`` then parses
    these tags manually.

Why ``include_contents='none'``:
    All context the LLM needs is injected via the dynamic instruction from
    workflow state (blueprint, validation errors). Conversation
    history would only add noise and consume tokens.
"""



from google.adk.agents import Agent
from google.adk.models import Gemini
from google.genai import types
from ..config import settings
from typing import Dict, Any, List, Optional, Union

from a2ui.schema.manager import A2uiSchemaManager
from a2ui.basic_catalog.provider import BasicCatalog
from a2ui.schema.constants import VERSION_0_9_1

# Initialize the A2UI schema manager with the v0.9.1 specification and the
# basic component catalog. This manager is used at prompt-construction time
# (not at import time) to generate the system prompt that teaches the LLM
# about A2UI's JSON schema, available components, and valid property values.
schema_manager = A2uiSchemaManager(
    version=VERSION_0_9_1,
    catalogs=[BasicCatalog.get_config(version=VERSION_0_9_1)]
)

def dynamic_instruction(ctx):
    """Dynamically builds the system prompt for A2UI schema generation.
    
    Reads the `blueprint` from state, and applies strict A2UI
    rendering rules. Crucially, it provides a full BMI calculator example to
    teach the LLM the exact required JSON structure (flat component tree, specific
    binding formats, etc.).
    """
    # ------------------------------------------------------------------
    # 1. Extract and serialize the blueprint from workflow state.
    #    The blueprint may arrive as a Pydantic model (from blueprint_generator),
    #    a dict (if deserialized from JSON state), or a raw string.
    # ------------------------------------------------------------------
    blueprint = ctx.state.get("blueprint", "")

    if hasattr(blueprint, "model_dump_json"):
        # Pydantic v2 model — use its built-in JSON serializer for fidelity.
        blueprint = blueprint.model_dump_json()
    elif isinstance(blueprint, dict):
        import json
        blueprint = json.dumps(blueprint, indent=2)
    else:
        blueprint = str(blueprint)


    # ------------------------------------------------------------------
    # 2. Construct the A2UI generation rules and in-context example.
    #
    # The rules are ordered by severity: format → structure → data binding
    # → component-specific → validation → example → closing reminder.
    # Each rule is prefixed with a capitalized label (CRITICAL, IMPORTANT,
    # etc.) because empirical testing showed that LLMs respect all-caps
    # directives more reliably than lowercase ones.
    # ------------------------------------------------------------------
    ui_desc = (
        "Generate a complete A2UI JSON payload that represents this calculator.\n"
        # [WHY] Normalizes outputs across models (some use ```json, some use raw text) for the SDK parser.
        "TAG WRAPPING REQUIREMENT: You MUST wrap the entire JSON payload in `<a2ui-json>` and `</a2ui-json>` tags. Output ONLY the tagged JSON payload, without any surrounding conversational text, explanations, or markdown code blocks (unless the tags are inside it).\n"
        # [WHY] Ensures the UI has a standard header.
        "HEADER COMPONENTS REQUIREMENT: You MUST include two Text components at the very top of your \"components\" list: first, a component with ID \"title-text\" containing the user-oriented title, and second, a component with ID \"description-text\" containing the user-oriented description.\n"
        # --- Output format: single JSON array with both messages ---
        "IMPORTANT: You MUST output exactly ONE JSON array containing BOTH an `updateComponents` message and an `updateDataModel` message. Do not split them into separate blocks.\n"
        # --- Flat tree: the #1 most common LLM mistake with A2UI ---
        # [WHY] A2UI Protocol constraint: Recursive JSON nesting causes deep validation failures; flat is required.
        "CRITICAL: The component tree MUST BE COMPLETELY FLAT. Container components (Column, Row, Card, Button) CANNOT contain inline object definitions for their children. You MUST reference children exclusively by their string IDs and place all actual component objects at the root level of the components array.\n"
        # --- Data binding syntax: object format, NOT string templates ---
        # [WHY] A2UI v0.9+ syntax requires explicit `{"path": "/var"}` object binding rather than string templates.
        "DATA BINDING SYNTAX: A2UI uses JSON objects for state binding. You MUST NOT use string templates like `${/weight}`. If you use `${/weight}` the validation will CRASH. You MUST strictly use the object format: `{ \"path\": \"/weight\" }` for bindings.\n"
        # --- Result display binding (same syntax, but for output Text) ---
        "TEXT COMPONENT RESULT BINDING: For Text components that display calculation results, you MUST use object binding (e.g., `\"text\": {\"path\": \"/bmi_value\"}`). The path MUST exactly match the output variable keys defined in the backend blueprint. Do NOT use string interpolation like `${/bmi_value}` or `{{bmi_value}}`.\n"
        # --- Default values prevent an empty-looking UI on first load ---
        "DEFAULT VALUES: If appropriate, input values in the `updateDataModel` message should have reasonable default values instead of null so the UI isn't completely empty when first loaded.\n"
        # --- Dual input+slider pattern for numeric ranges ---
        "SLIDERS FOR RANGES: For values which have a reasonable real-life range, create both an input field and a slider bound to the same parameter (as demonstrated in the example below).\n"
        # --- Slider constraint: only integer ranges are supported ---
        "SLIDER LIMITATIONS: Create slider components only if they can be represented in integer range, otherwise - use input field only. Use strict integer values for `min` and `max` (e.g., `10` and `300` rather than `10.0` or `10.5`)"
        # --- ChoicePicker always stores arrays, even for single-select ---
        # [WHY] Explains how to handle arrays in A2UI bindings, matching script_generator logic.
        "CHOICEPICKER BINDING: ChoicePicker stores its selections as an array of strings, even when variant is 'mutuallyExclusive'. Initialize these values as arrays (e.g., `\"weight_unit\": [\"kg\"]`). When passing these in the calculate button payload, map directly (e.g., `{\"path\": \"/weight_unit\"}`). Do NOT use array indexing.\n"
        # --- Honor blueprint component_type exactly ---
        # [WHY] Connects the visual layout directly to the script_generator's expectations.
        "EXACT COMPONENT MAPPING: The backend blueprint's `component_type` (e.g., 'ChoicePicker', 'TextField', 'Slider', 'CheckBox') MUST be respected. If a parameter specifies `component_type: \"ChoicePicker\"`, you MUST use an A2UI `ChoicePicker` component. This guarantees the UI matches the python script's expectations.\n"
        # --- Client-side validation via checks array ---
        # [WHY] Ensures client-side validation logic matches the backend restrictions.
        "INPUT VALIDATION CHECKS: For input components (like TextField), you MUST define a `checks` array if validation rules (like required, min_value, max_value, pattern) are specified in the parameter definitions of the blueprint. Set up checks using function calls (e.g., `call: \"required\"`, `call: \"numeric\"` with `min` and `max` arguments, or `call: \"regex\"` with a `pattern` argument) wrapped inside the `condition` property of each CheckRule, and include user-friendly error messages (e.g. \"Weight is required.\").\n"
        # ---------------------------------------------------------------
        # IN-CONTEXT BMI CALCULATOR EXAMPLE
        #
        # [WHY] An exact working example is the most reliable way to teach LLMs complex syntax like A2UI.
        # This ~300-line JSON example is the single most important part of
        # the prompt. It teaches the LLM by demonstration rather than by
        # description, covering:
        #   - Flat component tree with string ID references
        #   - Object binding syntax ({"path": "/var"})
        #   - Dual input + slider pattern
        #   - ChoicePicker with array-valued initial data
        #   - Validation checks (required, numeric with min/max)
        #   - Button action with event payload
        #   - Result display via bound Text components
        #   - updateDataModel with sensible default values
        # ---------------------------------------------------------------
        "EXAMPLE OF A COMPLETE, CORRECT, FULLY FLAT A2UI PAYLOAD:\n"
        "```json\n"
        "[\n"
        "  {\n"
        "    \"version\": \"v0.9\",\n"
        "    \"updateComponents\": {\n"
        "      \"surfaceId\": \"calculator-surface\",\n"
        "      \"components\": [\n"
        "        {\n"
        "          \"id\": \"title-text\",\n"
        "          \"component\": \"Text\",\n"
        "          \"variant\": \"h4\",\n"
        "          \"text\": \"Body Mass Index (BMI) Calculator\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"description-text\",\n"
        "          \"component\": \"Text\",\n"
        "          \"variant\": \"body\",\n"
        "          \"text\": \"The Body Mass Index (BMI) calculator determines your health category by calculating the relationship between your weight and height, offering support for both metric and imperial measurement units.\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"root\",\n"
        "          \"component\": \"Column\",\n"
        "          \"children\": [\n"
        "            \"main-card\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"main-card\",\n"
        "          \"component\": \"Card\",\n"
        "          \"child\": \"main-column\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"main-column\",\n"
        "          \"component\": \"Column\",\n"
        "          \"children\": [\n"
        "            \"title-text\",\n"
        "            \"description-text\",\n"
        "            \"weight-row\",\n"
        "            \"weight-slider\",\n"
        "            \"height-row\",\n"
        "            \"height-slider\",\n"
        "            \"calculate-button\",\n"
        "            \"results-card\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"weight-row\",\n"
        "          \"component\": \"Row\",\n"
        "          \"align\": \"end\",\n"
        "          \"children\": [\n"
        "            \"weight-input\",\n"
        "            \"weight-unit-picker\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"weight-input\",\n"
        "          \"component\": \"TextField\",\n"
        "          \"label\": \"Weight\",\n"
        "          \"variant\": \"number\",\n"
        "          \"value\": {\n"
        "            \"path\": \"/weight\"\n"
        "          },\n"
        "          \"weight\": 1,\n"
        "          \"checks\": [\n"
        "            {\n"
        "              \"condition\": {\n"
        "                \"call\": \"required\",\n"
        "                \"args\": {\n"
        "                  \"value\": {\n"
        "                    \"path\": \"/weight\"\n"
        "                  }\n"
        "                }\n"
        "              },\n"
        "              \"message\": \"Weight is required.\"\n"
        "            },\n"
        "            {\n"
        "              \"condition\": {\n"
        "                \"call\": \"numeric\",\n"
        "                \"args\": {\n"
        "                  \"value\": {\n"
        "                    \"path\": \"/weight\"\n"
        "                  },\n"
        "                  \"min\": 0.1,\n"
        "                  \"max\": 1000.0\n"
        "                }\n"
        "              },\n"
        "              \"message\": \"Weight must be between 0.1 and 1000.0.\"\n"
        "            }\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"weight-unit-picker\",\n"
        "          \"component\": \"ChoicePicker\",\n"
        "          \"label\": \"\",\n"
        "          \"variant\": \"mutuallyExclusive\",\n"
        "          \"displayStyle\": \"chips\",\n"
        "          \"value\": {\n"
        "            \"path\": \"/weight_unit\"\n"
        "          },\n"
        "          \"options\": [\n"
        "            {\n"
        "              \"label\": \"kg\",\n"
        "              \"value\": \"kg\"\n"
        "            },\n"
        "            {\n"
        "              \"label\": \"lb\",\n"
        "              \"value\": \"lb\"\n"
        "            }\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"weight-slider\",\n"
        "          \"component\": \"Slider\",\n"
        "          \"min\": 10.0,\n"
        "          \"max\": 300.0,\n"
        "          \"step\": 1.0,\n"
        "          \"value\": {\n"
        "            \"path\": \"/weight\"\n"
        "          }\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"height-row\",\n"
        "          \"component\": \"Row\",\n"
        "          \"align\": \"end\",\n"
        "          \"children\": [\n"
        "            \"height-input\",\n"
        "            \"height-unit-picker\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"height-input\",\n"
        "          \"component\": \"TextField\",\n"
        "          \"label\": \"Height\",\n"
        "          \"variant\": \"number\",\n"
        "          \"value\": {\n"
        "            \"path\": \"/height\"\n"
        "          },\n"
        "          \"weight\": 1,\n"
        "          \"checks\": [\n"
        "            {\n"
        "              \"condition\": {\n"
        "                \"call\": \"required\",\n"
        "                \"args\": {\n"
        "                  \"value\": {\n"
        "                    \"path\": \"/height\"\n"
        "                  }\n"
        "                }\n"
        "              },\n"
        "              \"message\": \"Height is required.\"\n"
        "            },\n"
        "            {\n"
        "              \"condition\": {\n"
        "                \"call\": \"numeric\",\n"
        "                \"args\": {\n"
        "                  \"value\": {\n"
        "                    \"path\": \"/height\"\n"
        "                  },\n"
        "                  \"min\": 0.1,\n"
        "                  \"max\": 300.0\n"
        "                }\n"
        "              },\n"
        "              \"message\": \"Height must be between 0.1 and 300.0.\"\n"
        "            }\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"height-unit-picker\",\n"
        "          \"component\": \"ChoicePicker\",\n"
        "          \"label\": \"\",\n"
        "          \"variant\": \"mutuallyExclusive\",\n"
        "          \"displayStyle\": \"chips\",\n"
        "          \"value\": {\n"
        "            \"path\": \"/height_unit\"\n"
        "          },\n"
        "          \"options\": [\n"
        "            {\n"
        "              \"label\": \"m\",\n"
        "              \"value\": \"m\"\n"
        "            },\n"
        "            {\n"
        "              \"label\": \"cm\",\n"
        "              \"value\": \"cm\"\n"
        "            },\n"
        "            {\n"
        "              \"label\": \"in\",\n"
        "              \"value\": \"in\"\n"
        "            }\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"height-slider\",\n"
        "          \"component\": \"Slider\",\n"
        "          \"min\": 30.0,\n"
        "          \"max\": 250.0,\n"
        "          \"step\": 1.0,\n"
        "          \"value\": {\n"
        "            \"path\": \"/height\"\n"
        "          }\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"calculate-button\",\n"
        "          \"component\": \"Button\",\n"
        "          \"variant\": \"primary\",\n"
        "          \"child\": \"calculate-button-text\",\n"
        "          \"action\": {\n"
        "            \"event\": {\n"
        "              \"name\": \"calculate\",\n"
        "              \"context\": {\n"
        "                \"weight\": {\n"
        "                  \"path\": \"/weight\"\n"
        "                },\n"
        "                \"weight_unit\": {\n"
        "                  \"path\": \"/weight_unit\"\n"
        "                },\n"
        "                \"height\": {\n"
        "                  \"path\": \"/height\"\n"
        "                },\n"
        "                \"height_unit\": {\n"
        "                  \"path\": \"/height_unit\"\n"
        "                }\n"
        "              }\n"
        "            }\n"
        "          }\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"calculate-button-text\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": \"Calculate BMI\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"results-card\",\n"
        "          \"component\": \"Card\",\n"
        "          \"child\": \"results-column\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"results-column\",\n"
        "          \"component\": \"Column\",\n"
        "          \"children\": [\n"
        "            \"bmi-result-row\",\n"
        "            \"category-result-row\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"bmi-result-row\",\n"
        "          \"component\": \"Row\",\n"
        "          \"justify\": \"spaceBetween\",\n"
        "          \"children\": [\n"
        "            \"bmi-result-label\",\n"
        "            \"bmi-result-value\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"bmi-result-label\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": \"BMI\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"bmi-result-value\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": {\n"
        "            \"path\": \"/bmi\"\n"
        "          }\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"category-result-row\",\n"
        "          \"component\": \"Row\",\n"
        "          \"justify\": \"spaceBetween\",\n"
        "          \"children\": [\n"
        "            \"category-result-label\",\n"
        "            \"category-result-value\"\n"
        "          ]\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"category-result-label\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": \"Category\"\n"
        "        },\n"
        "        {\n"
        "          \"id\": \"category-result-value\",\n"
        "          \"component\": \"Text\",\n"
        "          \"text\": {\n"
        "            \"path\": \"/category\"\n"
        "          }\n"
        "        }\n"
        "      ]\n"
        "    }\n"
        "  },\n"
        "  {\n"
        "    \"version\": \"v0.9\",\n"
        "    \"updateDataModel\": {\n"
        "      \"surfaceId\": \"calculator-surface\",\n"
        "      \"value\": {\n"
        "        \"weight\": 70.0,\n"
        "        \"weight_unit\": [\"kg\"],\n"
        "        \"height\": 170.0,\n"
        "        \"height_unit\": [\"cm\"],\n"
        "        \"bmi\": null,\n"
        "        \"category\": null\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "]\n"
        "```\n"
        # --- Final reminders to constrain output format ---
        "Ensure the components map to all inputs and results defined in the blueprint, and include a calculate button that triggers the 'calculate' action.\n"
        "DO NOT output any conversational text, explanations, or apologies. You MUST wrap the entire JSON payload in `<a2ui-json>` and `</a2ui-json>` tags. Output ONLY the tagged JSON payload."
    )
    
    # ------------------------------------------------------------------
    # 3. Retry feedback loop: append validation errors from previous attempt.
    # On retry loops, append the specific schema violation errors so the LLM can fix them.
    # ------------------------------------------------------------------
    validation_err = ctx.state.get("ui_validation_error", "")
    if validation_err:
        ui_desc += f"\n\nCRITICAL ERROR IN PREVIOUS ATTEMPT: Your previous JSON payload failed validation with these exact errors:\n{validation_err}\n\nYOU MUST FIX THESE ERRORS and strictly adhere to the flat component tree requirement.\nAGAIN: NO explanations, NO apologies. JUST RETURN THE FIXED JSON SCHEMA."

    # ------------------------------------------------------------------
    # 4. Assemble the final system prompt via the A2UI SDK.
    # Use the A2UI SDK to weave the standard declarative catalog logic into the prompt.
    # ------------------------------------------------------------------
    return schema_manager.generate_system_prompt(
        role_description="You are a frontend generator that outputs a valid A2UI declarative JSON schema payload.",
        workflow_description=(
            "Generate a complete A2UI JSON payload for a calculator based STRICTLY on this blueprint:\n\n"
            f"{blueprint}"
        ),
        ui_description=ui_desc,
        include_schema=True,
        include_examples=True,
        allowed_components=["Column", "Row", "Card", "TextField", "Slider", "ChoicePicker", "Text", "Button"]
    )

# ---------------------------------------------------------------------------
# Agent Node Definition
#
# This is registered as a node in the Manyculator workflow graph. The workflow
# engine calls it after blueprint_generator completes, and routes its output
# to ui_schema_validator for parsing and validation.
# ---------------------------------------------------------------------------
ui_schema_generator = Agent(
    name="ui_schema_generator",
    model=settings.model_coding,
    # include_contents='none': Ignore conversation history entirely. All
    # context comes from the dynamic instruction built from workflow state.
    # This keeps the prompt focused and avoids wasting tokens on prior turns.
    include_contents='none',
    # instruction is a callable — ADK invokes dynamic_instruction(ctx) on
    # every execution, allowing the prompt to reflect the latest state
    # (blueprint, and any validation errors from prior attempts).
    instruction=dynamic_instruction,
    # INTENTIONALLY no output_schema. Passing it forces a function call object,
    # which breaks raw JSON generation. Instead, we prompt the LLM to wrap its 
    # JSON in <a2ui-json> tags and parse them downstream in ui_schema_validator.
)
