"""Calculator Blueprint Data Model.

This module defines the structured contract (Blueprint) that is generated by the
intent analysis LLM. It acts as the single source of truth for the entire pipeline,
guiding both the script generator and UI schema generator to ensure they build
compatible halves of the final calculator.
"""

from typing import List
from pydantic import BaseModel, Field
from .calculator import ParameterDef

class CalculatorBlueprint(BaseModel):
    """The structured intent analysis defining what the calculator must do."""
    is_calculator: bool = Field(description="True if the user's intent is to create a calculator or converter. False otherwise.")
    reasoning: str = Field(description="Brief reasoning for the classification.")
    calculator_name: str = Field(default="", description="Suggested name for the calculator.")
    calculator_description: str = Field(default="", description="Suggested brief description of what the calculator computes and how.")
    parameters: List[ParameterDef] = Field(default_factory=list, description="List of all parameters required for the calculator, including inputs and results. Must be exhaustive.")
    computation_logic: str = Field(default="", description="Detailed, step-by-step description of the mathematical logic or algorithm to implement.")
    edge_cases: List[str] = Field(default_factory=list, description="List of boundary conditions or invalid states to handle (e.g. division by zero, negative amounts).")
    error_handling_strategy: str = Field(default="", description="Explicit rule for what the output dictionary should look like when an error occurs (e.g., return {'error': 'message'}).")
